api_host = ":4001"
api_rate_limit = 100
websocket_host = ":4002"
redis_url = "redis://127.0.0.1:6380/0"
database_url = "postgres://postgres:postgres@localhost:5434/postgres?sslmode=disable"
jwt_secret = "test"
factory_address = "0x00000000000000000000000000"
broker_address = "0x00000000000000000000000000"
watcher_id = 1

[blockchain]
interval = "5s"
timeout = "5s"
provider_url = "http://server10.jy.mcarlo.com:8747"
