api_host = ":4001"
api_rate_limit = 100
websocket_host = ":4002"
redis_url = "redis://127.0.0.1:6380/0"
database_url = "postgres://postgres:postgres@localhost:5434/postgres?sslmode=disable"
jwt_secret = "test"
factory_address = "0x00000000000000000000000000"
broker_address = "0x00000000000000000000000000"
watcher_id = 1
rpc_host = "127.0.0.1:4003"

[gas_station]
url = "https://ethgasstation.info/api/ethgasAPI.json"
timeout = "5s"
gas_level = "average"
gas_limit = 5000000


[blockchain]
chain_type = "ethereum"
interval = "5s"
timeout = "5s"
provider_url = "http://server10.jy.mcarlo.com:8747"
password = "qedaxzop"

[token_min_amounts]
    [token_min_amounts.ETH] 
     amount = 10.0