name: Go

on:
  push:
    tags:
    - v*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Set up Go 1.16.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
      id: go
    - name: Go env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v1 # without submodules
    - name: Disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: Enable the local store credential helper
      run: git config --global --add credential.helper store

    - name: Add credential
      run: |
        echo "https://x-access-token:${{ secrets.CLONE_ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: Tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Set GOPRIVATE
      run: 'go env -w GOPRIVATE=github.com/mcarloai'
    - name: Build
      run: |
        mkdir -p dist
        go build -v -o dist ./cli/mai3-l2-relayer ./cli/mai3-order-relayer
    - name: Upload to aliyun
      run: |
        ls -l dist
        docker login --username=${{ secrets.ALI_REPO_USER }} --password=${{ secrets.ALI_REPO_PASSWORD }} registry.ap-northeast-1.aliyuncs.com
        docker build -t registry.ap-northeast-1.aliyuncs.com/mcdex/mai-v3-broker:${{ steps.get_version.outputs.VERSION }} .
        docker push registry.ap-northeast-1.aliyuncs.com/mcdex/mai-v3-broker:${{ steps.get_version.outputs.VERSION }}
